--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-12-27 10:20:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 93339)
-- Name: Notes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Notes" (
    "Id" integer NOT NULL,
    "Text" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RemovedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone
);


ALTER TABLE public."Notes" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 93338)
-- Name: Notes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Notes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 93333)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4842 (class 0 OID 93339)
-- Dependencies: 217
-- Data for Name: Notes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Notes" ("Id", "Text", "CreatedAt", "RemovedAt") FROM stdin;
1	First Note	2024-12-27 10:18:37.847+05	\N
2	Second Note	2024-12-27 10:19:13.739+05	\N
\.


--
-- TOC entry 4840 (class 0 OID 93333)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20241227042403_Init	9.0.0
20241227043633_AddRemovedAt	9.0.0
20241227051753_MakeRemovedAtNullable	9.0.0
\.


--
-- TOC entry 4848 (class 0 OID 0)
-- Dependencies: 216
-- Name: Notes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Notes_Id_seq"', 2, true);


--
-- TOC entry 4696 (class 2606 OID 93345)
-- Name: Notes PK_Notes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notes"
    ADD CONSTRAINT "PK_Notes" PRIMARY KEY ("Id");


--
-- TOC entry 4694 (class 2606 OID 93337)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2024-12-27 10:20:59

--
-- PostgreSQL database dump complete
--

